# -*- coding: utf-8 -*-
"""
/***************************************************************************
 TrnstAnlys
                                 A QGIS plugin
 View transit stop coverage statistics
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-04-24
        copyright            : (C) 2024 by Team Transit Analysis
        email                : britt.119@osu.edu
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load TrnstAnlys class from file TrnstAnlys.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .transit_analysis_tool import TrnstAnlys
    return TrnstAnlys(iface)
